### PR TITLE
User dashboard

### PR DESCRIPTION
**Pull request by julieflament**
completed #70

### CODE REVIEW

**Comment by komalsingh0925** [comment]
I approve, I also worked on the nav-bar.html in this branch, in order to integrate the user dashboard with the nav-bar. This makes it so that the nav bar is positioned on top of the user dashboard page.  Moving forward, we've decided that this is the way to link all pages with the nav bar. By adding this code underneath the closing header tag. "</header"

"<iframe src="/code/front-end/user-dashboard/user-dashboard.html" style="width:100%; height: 100%; border:none;"></iframe>"

**Comment by komalsingh0925** [comment]
Pls note, when running this for testing purpose, pls run nav-bar-html.html

**Comment by danglakshay** [comment]
The design looks great! Good job on using dummy data to make an accurate representation of what the visualizations will look like.

**Review by noahstaz — APPROVED** [review]
The code looks good and we will edit the user dashboard further, once we implement the backed.

**Comment by julieflament** [comment]
thanks for the approval!

**Pull request merged**
