### PR TITLE
Database/initialize new db

### PR DESCRIPTION
**Pull request by noahstaz**
Completed #71 

Created the tables with mock data, and I also modified the user data table design to fit the project requirements. I also wrote a test file for the data and ensured that all the test cases so that our data works properly for the next sprint.

### CODE REVIEW

**Comment by noahstaz** [comment]
Forgot to mention there is a git ignore file I included as well to make it easier for the team to collaborate

**Comment by komalsingh0925** [comment]
i approve!

**Comment by danglakshay** [comment]
Looks Good!  I approve!

**Review by danglakshay — APPROVED** [review]
Code Looks good!

**Review by trevorwinser — APPROVED** [review]

**Pull request merged**
