### PR TITLE
Front end/alert system

### PR DESCRIPTION
**Pull request by noahstaz**
-Completed #91 The front end and testing is included
-Images have been moved to the static folder
-Two new downloads in the requirements.txt for front-end testing

### CODE REVIEW

**Comment by noahstaz** [comment]
http://127.0.0.1:5000/alerts for testing the view

**Comment by noahstaz** [comment]
If you want to run the test files there are now instructions on the team documentation

**Review by komalsingh0925 — APPROVED** [review]
Tests passed and the page looks great!

**Review by danglakshay — APPROVED** [review]
Test works fine! Great Job!

**Pull request merged**
