### PR TITLE
Functional navbars

### PR DESCRIPTION
**Pull request by trevorwinser**
1. Follow [flask.md](https://github.com/trevorwinser/Infinite-Loopers/blob/functional-navbars/Instructions/flask.md) to get server running
2. Verify register page has navbar
3. Sign in with Admin1 Password1 credentials
4. Verify admin page has navbar
5. Verify alert page has navbar

Testing and further implementation will come after predictions page is fully integrated into the server folder

#144 Part 1

### CODE REVIEW

**Review by komalsingh0925 — APPROVED** [review]
Looks good, just don't forget to also remove the side-panel

**Review by julieflament — CHANGES_REQUESTED** [review]
- create account doesn't show the actual picture for the nav bar
- in registration page, when you click log in, instead of signing up, it sends me to http://127.0.0.1:5000/login.html instead of http://127.0.0.1:5000/login

**Comment by trevorwinser** [comment]
> * create account doesn't show the actual picture for the nav bar
> * in registration page, when you click log in, instead of signing up, it sends me to http://127.0.0.1:5000/login.html instead of http://127.0.0.1:5000/login

Fixed!

**Review by julieflament — APPROVED** [review]

**Comment by trevorwinser** [comment]
> Looks good, just don't forget to also remove the side-panel, also in registration page when clicked on "already have account, log in" the page breaks as it sends to the html route

Fixed!

**Pull request merged**
