### PR TITLE
Preliminary Restructuring of Project Directory Structure

### PR DESCRIPTION
**Pull request by danglakshay**
#128 Complete

More work will be done during the sprint to make sure that the site runs with the new structure. This pull request is simply to apply the streamlines structure to the main branch, and to make sure that all code written from this point can fit into the structure.

### CODE REVIEW

**Review by noahstaz — COMMENTED** [review]
Restructuring looks good! Did you make sure that everything still worked properly afterwards?

**Review by noahstaz — CHANGES_REQUESTED** [review]
^ In addition to the above comment, take a look at the merge conflcits

**Review by komalsingh0925 — CHANGES_REQUESTED** [review]
Pls review the conflicts other than that looks neat

**Comment by danglakshay** [comment]
> Pls review the conflicts other than that looks neat

Conflicts reviewed and resolved.


> Restructuring looks good! Did you make sure that everything still worked properly afterwards?

Login and Registration are working alright with hurriscan.db, and more tests have been added.
The integration and linking of all the webpages will occur in a separate branch when this request is approved.

**Review by julieflament — CHANGES_REQUESTED** [review]
review/resolve the merge conflicts otherwise its good!

**Comment by danglakshay** [comment]
> review/resolve the merge conflicts otherwise its good!

Conflicts resolved.

**Pull request merged**
